version: "3.6"

services:

  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    networks:
      - elastic-net
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: "single-node"
      ELASTIC_PASSWORD: "test"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.0
    networks:
      - elastic-net
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: "http://search:9200"
    depends_on:
      - search

networks:
  elastic-net:
    external: true
    name: elastic-net
