version: "3.6"

services:

  docker:
    deploy:
      mode: global

  traefik:
    image: docker.elastic.co/beats/filebeat:7.6.0
    networks:
      - elastic-net
    environment:
      DOCKER_NODE_HOSTNAME: "{{.Node.Hostname}}"
      HOSTNAME_PATTERN: "test.localhost"
      ENV: "${ENV:-local}"
      ES_HOSTS: "[\"search:9200\"]"
      ES_USER: "elastic"
      ES_PASSWORD: "test"
      INDEX_PREFIX: "gui_filebeat_traefik_${ENV:-local}"
    user: root
    volumes:
      - traefik-logs:/var/log
      - ./config/filebeat-traefik.dev.yml:/usr/share/filebeat/filebeat.yml:cached
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager

volumes:
  traefik-logs:
    external: true
    name: traefik-logs
  filebeat-search-data:
    external: true
    name: filebeat-search-data
